name: _anypytools
channels:
  - anybody
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - h5py
  - cloud_sptheme=1.10.1.post20200504175005
  - setuptools
  - pydoe
  - tqdm
  - scipy
  - pygments_anyscript
  - pandas
  - ipywidgets
  - build
  - twine

